title: Refar-Blog
description: "A Jekyll Blog Theme For Refar"
author:
  name: "Refar"
  email: "812647742@qq.com"
  url: "https://ss7424refar.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 6
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Custom variables
owner : "Refar"
year : "2019"